version: 0.2

phases:
  install:
    commands: []
  build:
    commands: []
  post_build:
    commands:
      # Move to the correct Frontend directory (relative to the project root)
      - cd ../../../Frontend
      - aws s3 sync . s3://my-b1-frontend --exclude ".DS_Store" --exclude "README.md" --delete

artifacts:
  files:
    - ../../../Frontend/**/*
