version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9

  build:
    commands:
      - echo "Building Lambda deployment packages"
      # Go to LambdaFunctions directory (relative path)
      - cd ../../LambdaFunctions

      # Package index-photos Lambda
      - cp index-photos.py lambda_function.py
      - zip index-photos.zip lambda_function.py
      - rm lambda_function.py

      # Package search-photos Lambda
      - cp search-photos.py lambda_function.py
      - zip search-photos.zip lambda_function.py
      - rm lambda_function.py

  post_build:
    commands:
      - echo "Deploying to Lambda functions"
      - aws lambda update-function-code --function-name index-photos --zip-file fileb://index-photos.zip
      - aws lambda update-function-code --function-name search-photos --zip-file fileb://search-photos.zip

artifacts:
  files:
    - ../../LambdaFunctions/index-photos.zip
    - ../../LambdaFunctions/search-photos.zip
